### ISSUE TITLE
Internal audio recording is not working

### ISSUE THREAD

**Issue by ForgottenLight4415** [endmr11/ed_screen_recorder#34]

**Comment by ForgottenLight4415** [comment]
Any update on this?

**Comment by pmahala** [comment]
I am facing the same issue. How are you able to make it work @danglu999 ?

E/MediaRecorder( 6454): SurfaceMediaSource could not be initialized!
E/MediaRecorder( 6454): start called in an invalid state: 32
E/Video Error:( 6454): java.lang.RuntimeException: setAudioSource failed.
E/Video Error:( 6454): 	at android.media.MediaRecorder.setAudioSource(Native Method)
E/Video Error:( 6454): 	at com.hbisoft.hbrecorder.ScreenRecordService.initRecorder(ScreenRecordService.java:475)
E/Video Error:( 6454): 	at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:235)
E/Video Error:( 6454): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
E/Video Error:( 6454): 	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
E/Video Error:( 6454): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
E/Video Error:( 6454): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Video Error:( 6454): 	at android.os.Looper.loop(Looper.java:223)
E/Video Error:( 6454): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/Video Error:( 6454): 	at java.lang.reflect.Method.invoke(Native Method)
E/Video Error:( 6454): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/Video Error:( 6454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/Video Error:( 6454): java.lang.IllegalStateException: failed to get surface
E/Video Error:( 6454): 	at android.media.MediaRecorder.getSurface(Native Method)
E/Video Error:( 6454): 	at com.hbisoft.hbrecorder.ScreenRecordService.initVirtualDisplay(ScreenRecordService.java:535)
E/Video Error:( 6454): 	at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:259)
E/Video Error:( 6454): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
E/Video Error:( 6454): 	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
E/Video Error:( 6454): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
E/Video Error:( 6454): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Video Error:( 6454): 	at android.os.Looper.loop(Looper.java:223)
E/Video Error:( 6454): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/Video Error:( 6454): 	at java.lang.reflect.Method.invoke(Native Method)
E/Video Error:( 6454): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/Video Error:( 6454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/Video Error:( 6454): java.lang.IllegalStateException
E/Video Error:( 6454): 	at android.media.MediaRecorder.start(Native Method)
E/Video Error:( 6454): 	at com.hbisoft.hbrecorder.ScreenRecordService.onStartCommand(ScreenRecordService.java:305)
E/Video Error:( 6454): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
E/Video Error:( 6454): 	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
E/Video Error:( 6454): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
E/Video Error:( 6454): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Video Error:( 6454): 	at android.os.Looper.loop(Looper.java:223)
E/Video Error:( 6454): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/Video Error:( 6454): 	at java.lang.reflect.Method.invoke(Native Method)
E/Video Error:( 6454): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/Video Error:( 6454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
