### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by xxqwf** [endmr11/ed_screen_recorder#36]
![Uploading image.png…]()
When I hit Start recording, it executes the `HBRecorderOnComplete` method multiple times

**Comment by xxqwf** [comment]
<img width="1512" alt="WeChat4e53762ce13ae2f3f387138c64d0bafd" src="https://user-images.githubusercontent.com/57884068/191995313-a3ec53e3-01e7-4775-9823-81b45d89470a.png">

**Comment by xxqwf** [comment]
2022-09-23 23:13:34.766 27077-27077/com.healbone.patient E/Parcel: Reading a NULL string not supported here.
2022-09-23 23:13:36.609 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.610 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.613 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.614 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.630 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 24
2022-09-23 23:13:36.631 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 2
2022-09-23 23:13:36.631 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 23
2022-09-23 23:13:36.637 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 11
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 13
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 20
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 14
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 18
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 20
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 19
2022-09-23 23:13:36.640 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 16
2022-09-23 23:13:36.640 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 9
2022-09-23 23:13:36.715 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 5
2022-09-23 23:13:36.720 27077-27077/com.healbone.patient E/OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
2022-09-23 23:13:36.721 27077-27077/com.healbone.patient E/OplusCustomizeRestrictionManager: getForbidRecordScreenState Errorjava.lang.SecurityException: Check system signature permission Denial for pid=27077; uid = 10802
2022-09-23 23:13:36.728 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 8
2022-09-23 23:13:36.733 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.734 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.734 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.735 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.740 27077-27077/com.healbone.patient E/Video Start:: Start called
2022-09-23 23:13:36.741 27077-27077/com.healbone.patient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.healbone.patient, PID: 27077
    java.lang.IllegalStateException: Reply already submitted
        at l.a.d.b.f.c$e.a(DartMessenger.java:431)
        at l.a.e.a.j$a$a.a(MethodChannel.java:267)
        at h.d.a.a.b(EdScreenRecorderPlugin.java:200)
        at h.h.a.c$a.onReceiveResult(HBRecorder.java:374)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8283)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by xxqwf** [comment]
2022-09-23 23:13:34.568 27077-27077/com.healbone.patient D/ViewRootImpl: enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=518.0, y[0]=1510.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=23020229, downTime=23020229, deviceId=5, source=0x1002, displayId=0 }
2022-09-23 23:13:34.568 27077-27077/com.healbone.patient D/ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=518.0, y[0]=1510.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=23020229, downTime=23020229, deviceId=5, source=0x1002, displayId=0 }
2022-09-23 23:13:34.583 27077-27077/com.healbone.patient D/ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=518.0, y[0]=1510.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=23020229, downTime=23020229, deviceId=5, source=0x1002, displayId=0 }
2022-09-23 23:13:34.661 27077-27077/com.healbone.patient D/ViewRootImpl[MainActivity]: processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=518.0, y[0]=1510.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=23020326, downTime=23020229, deviceId=5, source=0x1002, displayId=0 }
2022-09-23 23:13:34.663 27077-27077/com.healbone.patient D/ViewRootImpl[MainActivity]: dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=518.0, y[0]=1510.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=23020326, downTime=23020229, deviceId=5, source=0x1002, displayId=0 }
2022-09-23 23:13:34.763 27077-27077/com.healbone.patient I/System.out: >>>>>>>>>>> 1
2022-09-23 23:13:34.766 27077-27077/com.healbone.patient E/Parcel: Reading a NULL string not supported here.
2022-09-23 23:13:34.788 27077-27077/com.healbone.patient I/UMLog: onPause@MainActivity
2022-09-23 23:13:34.824 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "
2022-09-23 23:13:34.824 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.572 27077-27077/com.healbone.patient I/UMLog: onResume@MainActivity
2022-09-23 23:13:36.597 27077-27318/com.healbone.patient D/MobclickAgent: 延续上一个会话: 49BA1CD054D608D062A827E3A73E9DEB
2022-09-23 23:13:36.601 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.601 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: ""
2022-09-23 23:13:36.601 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.601 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "-1"
2022-09-23 23:13:36.606 27077-27318/com.healbone.patient D/UMLog: 当前发送策略为: 间隔发送。间隔时间为：90秒。详见链接 https://developer.umeng.com/docs/66632/detail/66976?um_channel=sdk
2022-09-23 23:13:36.594 27077-27077/com.healbone.patient W/ealbone.patient: type=1400 audit(0.0:6680): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=14442 scontext=u:r:untrusted_app:s0:c34,c259,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.healbone.patient
2022-09-23 23:13:36.609 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.609 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: ""
2022-09-23 23:13:36.609 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.609 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.609 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "-1"
2022-09-23 23:13:36.610 27077-27318/com.healbone.patient D/MobclickAgent: 数据发送策略 : ReportByInterval
2022-09-23 23:13:36.610 27077-27318/com.healbone.patient D/UMLog: 当前发送策略为: 间隔发送。间隔时间为：90秒。详见链接 https://developer.umeng.com/docs/66632/detail/66976?um_channel=sdk
2022-09-23 23:13:36.610 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.594 27077-27077/com.healbone.patient W/ealbone.patient: type=1400 audit(0.0:6681): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=14442 scontext=u:r:untrusted_app:s0:c34,c259,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.healbone.patient
2022-09-23 23:13:36.613 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.614 27077-27077/com.healbone.patient E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-09-23 23:13:36.604 27077-27077/com.healbone.patient W/ealbone.patient: type=1400 audit(0.0:6682): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=14442 scontext=u:r:untrusted_app:s0:c34,c259,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.healbone.patient
2022-09-23 23:13:36.604 27077-27077/com.healbone.patient W/ealbone.patient: type=1400 audit(0.0:6683): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=14442 scontext=u:r:untrusted_app:s0:c34,c259,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.healbone.patient
2022-09-23 23:13:36.627 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::CreateSpace -- create new namespace oppoex
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::CreateSpace -- executable_path = /system/bin/app_process64
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::GetCurrentSection -- ld_config_file_path = /linkerconfig/ld.config.txt
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::CreateSpace -- section = system
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::ReadLink --  read /system/etc/public.libraries.txt success!
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::ReadLink --  read /apex/com.android.vndk.v30/etc/llndk.libraries.30.txt success!
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::ReadLink --  read /system_ext/oppoex/public.libraries-oppoex.txt success!
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::ReadLink --  read /apex/com.android.vndk.v30/etc/vndksp.libraries.30.txt success!
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::ReadLink --  read /vendor/etc/public.libraries.txt success!
2022-09-23 23:13:36.628 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::CreateSpace -- paths = /my_company/lib64/oppoex:/my_carrier/lib64/oppoex:/my_region/lib64/oppoex:/my_product/lib64/oppoex:/system_ext/lib64/oppoex:/system/lib64/oppoex
2022-09-23 23:13:36.629 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::CreateSpace -- link default : libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:libc.so:libcamera2ndk.so:libdl.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libicui18n.so:libicuuc.so:libjnigraphics.so:liblog.so:libmediandk.so:libm.so:libnativewindow.so:libneuralnetworks.so:libOpenMAXAL.so:libOpenSLES.so:libRS.so:libstdc++.so:libsync.so:libvulkan.so:libwebviewchromium_plat_support.so:libz.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libRS.so:libandroid_net.so:libbinder_ndk.so:libc.so:libcgrouprc.so:libclang_rt.asan-aarch64-android.so:libclang_rt.asan-arm-android.so:libdl.so:libft2.so:liblog.so:libm.so:libmediandk.so:libnativewindow.so:libneuralnetworks.so:libselinux.so:libsync.so:libvndksupport.so:libvulkan.so:libbinder.so
2022-09-23 23:13:36.629 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::CreateSpace -- link sphal : libqti-perfd-client.so:libadsprpc.so:libcdsprpc.so:libsdsprpc.so:libfastcvopt.so:liblistensoundmodel2.so:libOpenCL.so:libnpu.so:libhta_hexagon_runtime.so:libAlgoProcess.so:libancbase_rt_bokeh.so:libAncHumBokeh.so:libsnpe_loader.so:libstblur_api.so:libstdc++.so:libAncHumVideoBase.so:libmidasserviceintf.so:libarcsoft_scbokeh_video.so
2022-09-23 23:13:36.629 27077-27077/com.healbone.patient I/ealbone.patien: OPPOLoadFrame::CreateSpace -- link vndk : android.hardware.common-V1-ndk_platform.so:android.hardware.graphics.common-V1-ndk_platform.so:android.hardware.graphics.common@1.0.so:android.hardware.graphics.common@1.1.so:android.hardware.graphics.common@1.2.so:android.hardware.graphics.mapper@2.0.so:android.hardware.graphics.mapper@2.1.so:android.hardware.graphics.mapper@3.0.so:android.hardware.graphics.mapper@4.0.so:android.hardware.renderscript@1.0.so:android.hidl.memory.token@1.0.so:android.hidl.memory@1.0-impl.so:android.hidl.memory@1.0.so:android.hidl.safe_union@1.0.so:libRSCpuRef.so:libRSDriver.so:libRS_internal.so:libbacktrace.so:libbase.so:libbcinfo.so:libblas.so:libc++.so:libcompiler_rt.so:libcutils.so:libgralloctypes.so:libhardware.so:libhidlbase.so:libhidlmemory.so:libion.so:libjsoncpp.so:liblzma.so:libprocessgroup.so:libunwindstack.so:libutils.so:libutilscallstack.so:libz.so
2022-09-23 23:13:36.630 27077-27077/com.healbone.patient D/ealbone.patien: OplusTpCompLogExProxy::getOplusTpCompLogEx -- exp != NULL
2022-09-23 23:13:36.630 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 24
2022-09-23 23:13:36.631 27077-27077/com.healbone.patient I/MediaRecorder: setVideoSource() vs = 2
2022-09-23 23:13:36.631 27077-27077/com.healbone.patient I/MediaRecorder: init()
2022-09-23 23:13:36.631 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 2
2022-09-23 23:13:36.631 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 23
2022-09-23 23:13:36.637 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 11
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient I/MediaRecorder: setOutputFormat() of = 2
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 13
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 20
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient I/MediaRecorder: setVideoEncoder() ve = 0
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 14
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient D/MediaRecorder: setVideoSize(1080, 2400)
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 18
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 20
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 19
2022-09-23 23:13:36.638 27077-27077/com.healbone.patient D/MediaRecorder: mHypnusCtrl is true
2022-09-23 23:13:36.640 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 16
2022-09-23 23:13:36.640 27077-27077/com.healbone.patient I/MediaRecorder: prepare()
2022-09-23 23:13:36.640 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 9
2022-09-23 23:13:36.648 27077-27318/com.healbone.patient D/MobclickAgent: 延续上一个会话: 49BA1CD054D608D062A827E3A73E9DEB
2022-09-23 23:13:36.651 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.651 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: ""
2022-09-23 23:13:36.651 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.651 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "-1"
2022-09-23 23:13:36.652 27077-27318/com.healbone.patient D/UMLog: 当前发送策略为: 间隔发送。间隔时间为：90秒。详见链接 https://developer.umeng.com/docs/66632/detail/66976?um_channel=sdk
2022-09-23 23:13:36.654 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.654 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: ""
2022-09-23 23:13:36.655 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.655 27077-27318/com.healbone.patient W/SQLiteLog: (28) double-quoted string literal: "-1"
2022-09-23 23:13:36.655 27077-27318/com.healbone.patient D/MobclickAgent: 数据发送策略 : ReportByInterval
2022-09-23 23:13:36.656 27077-27318/com.healbone.patient D/UMLog: 当前发送策略为: 间隔发送。间隔时间为：90秒。详见链接 https://developer.umeng.com/docs/66632/detail/66976?um_channel=sdk
2022-09-23 23:13:36.714 27077-27077/com.healbone.patient W/MediaProjectionManager: 2022-09-23 23:13:36<Unkown-labelRes>[picture][com.healbone.patient]:[new MediaProjection(..)]
2022-09-23 23:13:36.715 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 5
2022-09-23 23:13:36.720 27077-27077/com.healbone.patient E/OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
2022-09-23 23:13:36.721 27077-27077/com.healbone.patient E/OplusCustomizeRestrictionManager: getForbidRecordScreenState Errorjava.lang.SecurityException: Check system signature permission Denial for pid=27077; uid = 10802
2022-09-23 23:13:36.728 27077-27077/com.healbone.patient I/MediaRecorder: start() enter +++
2022-09-23 23:13:36.728 27077-27077/com.healbone.patient E/CheckPermission: media_record-code= 8
2022-09-23 23:13:36.732 27077-27077/com.healbone.patient I/MediaRecorder: start() end; use totalTime = 4326 Us
2022-09-23 23:13:36.733 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.734 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.734 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.734 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.734 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.735 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.735 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.735 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.735 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.735 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.736 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.737 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.738 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.739 27077-27077/com.healbone.patient E/Video Complete:: Complete called
2022-09-23 23:13:36.740 27077-27077/com.healbone.patient I/System.out: =================== HBRecorderOnComplete ===================
2022-09-23 23:13:36.740 27077-27077/com.healbone.patient I/System.out: Error:Reply already submitted
2022-09-23 23:13:36.740 27077-27077/com.healbone.patient E/Video Start:: Start called
2022-09-23 23:13:36.740 27077-27077/com.healbone.patient D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2022-09-23 23:13:36.741 27077-27077/com.healbone.patient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.healbone.patient, PID: 27077
    java.lang.IllegalStateException: Reply already submitted
        at l.a.d.b.f.c$e.a(DartMessenger.java:431)
        at l.a.e.a.j$a$a.a(MethodChannel.java:267)
        at h.d.a.a.b(EdScreenRecorderPlugin.java:200)
        at h.h.a.c$a.onReceiveResult(HBRecorder.java:374)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8283)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
2022-09-23 23:13:36.747 27077-27149/com.healbone.patient I/flutter:       >>> Start Record Response Output:  
2022-09-23 23:13:36.749 27077-27149/com.healbone.patient I/flutter:       File: File: '/data/user/0/com.healbone.patient/app_flutter/Eren-2022-09-23-23-13-34.mp4' 
2022-09-23 23:13:36.749 27077-27149/com.healbone.patient I/flutter:       Event Name: stopRecordScreen  
2022-09-23 23:13:36.750 27077-27149/com.healbone.patient I/flutter:       Progressing: false 
2022-09-23 23:13:36.751 27077-27149/com.healbone.patient I/flutter:       Message: Paused Video 
2022-09-23 23:13:36.752 27077-27149/com.healbone.patient I/flutter:       Success: true 
2022-09-23 23:13:36.753 27077-27149/com.healbone.patient I/flutter:       Video Hash: 4adb81903b5211edb34e3d5a2e61c447 
2022-09-23 23:13:36.753 27077-27149/com.healbone.patient I/flutter:       Start Date: 1663946014761775 
2022-09-23 23:13:36.753 27077-27149/com.healbone.patient I/flutter:       End Date: 0
2022-09-23 23:13:36.753 27077-27149/com.healbone.patient I/flutter:       
2022-09-23 23:13:36.854 27077-27077/? E/UMLog: ┌───────────────────问题─────────────────────────────────────────────────────────────────────────────
2022-09-23 23:13:36.854 27077-27077/? E/UMLog: │     对于页面HBTaskListPage，onPageStart和onPageEnd调用对的参数不一致。
2022-09-23 23:13:36.854 27077-27077/? E/UMLog: ├───────────────────解决方案─────────────────────────────────────────────────────────────────────────────
2022-09-23 23:13:36.854 27077-27077/? E/UMLog: │     对于同一个页面，请先调用onPageStart，再调用onPageEnd。详见链接 https://developer.umeng.com/docs/66632/detail/66975?um_channel=sdk
2022-09-23 23:13:36.854 27077-27077/? E/UMLog: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-09-23 23:13:36.884 27077-27077/? W/SQLiteLog: (28) double-quoted string literal: "
2022-09-23 23:13:36.884 27077-27077/? W/SQLiteLog: (28) double-quoted string literal: "49BA1CD054D608D062A827E3A73E9DEB"
2022-09-23 23:13:36.926 27077-27077/? I/Process: Sending signal. PID: 27077 SIG: 9

**Comment by xxqwf** [comment]
@endmr11  Please take a look. Thank you

**Comment by ThuyenPV** [comment]
I got the same issue, have you found the solution to solve it? @xxqwf

**Comment by BaherAlsaqa** [comment]
@endmr11

**Comment by endmr11** [comment]
Version 0.0.13 has been released. Could you please check again and report back to me?
