### ISSUE TITLE
Reply already submitted

### ISSUE THREAD

**Issue by BaherAlsaqa** [endmr11/ed_screen_recorder#41]
D/AndroidRuntime(22051): Shutting down VM
E/AndroidRuntime(22051): FATAL EXCEPTION: main
E/AndroidRuntime(22051): Process: com.win.app, PID: 22051
E/AndroidRuntime(22051): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(22051): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime(22051): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(22051): 	at com.ed_screen_recorder.ed_screen_recorder.EdScreenRecorderPlugin.HBRecorderOnStart(EdScreenRecorderPlugin.java:195)
E/AndroidRuntime(22051): 	at com.hbisoft.hbrecorder.HBRecorder$1.onReceiveResult(HBRecorder.java:375)
E/AndroidRuntime(22051): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime(22051): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(22051): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(22051): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(22051): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(22051): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22051): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(22051): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by BaherAlsaqa** [comment]
add try catch like this:

try {
    flutterResult.success(jsonObj.toString());
} catch (Exception e) {
    System.out.println("Error:" + e.getMessage());
}

**Comment by endmr11** [comment]
Version 0.0.13 has been released. Could you please check again and report back to me?
