### ISSUE TITLE
I added this share plugin and it crashed：appinio_social_share: ^0.2.1

### ISSUE THREAD

**Issue by tudosxxx** [endmr11/ed_screen_recorder#79]
D/AndroidRuntime( 7195): Shutting down VM
E/AndroidRuntime( 7195): FATAL EXCEPTION: main
E/AndroidRuntime( 7195): Process: com.giftools.itse, PID: 7195
E/AndroidRuntime( 7195): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7195): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 7195): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/AndroidRuntime( 7195): 	at com.ed_screen_recorder.ed_screen_recorder.EdScreenRecorderPlugin.HBRecorderOnStart(EdScreenRecorderPlugin.java:195)
E/AndroidRuntime( 7195): 	at com.hbisoft.hbrecorder.HBRecorder$1.onReceiveResult(HBRecorder.java:375)
E/AndroidRuntime( 7195): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime( 7195): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 7195): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7195): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 7195): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/AndroidRuntime( 7195): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7195): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime( 7195): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by tudosxxx** [comment]
error reson in AndroidManifest.xml  share setting.

**Comment by endmr11** [comment]
Version 0.0.13 has been released. Could you please check again and report back to me?
